### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by valkiriaaquatica** [Evantage-WS/lldap-kubernetes#2]
Hi,
first of all thanks for your good job maintainer the image! 
Second, have you ever thought of making a helm chart? I've  been working for a while with a own custom helm chart for this lldap installation  and as it is your work the one of maintaining the image, I would like to ask if there is some way we can upload a helm chart for making installation easier, I don't mind if we get mine and meka some modficiation and just publish it... 

Again thanks!

**Comment by valkiriaaquatica** [comment]
Oh I get it, I thought you were, I can PR the ones I was using to this repo as I assume is the only one related to LLDAP and Kubernetes

**Comment by Evantage-WS** [comment]
Sure, create a PR. I will look later this week

**Comment by Evantage-WS** [comment]
Merged
